apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: github-demo
  template:
    metadata:
      labels:
        app: github-demo
    spec:
      containers:
      - name: github-demo
        image: docker.io/vsmetgud/github-demo:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
