apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: github-demo-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: github-demo
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
